# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Top 10 FAIR Data & Software Things"
description:        "The Top 10 FAIR Data & Software Global Sprint was held online over the course of two-days (29-30 November 2018), where participants from around the world were invited to develop brief guides (stand alone, self paced training materials), called “Things”, that can be used by the research community to understand FAIR in different contexts as well as some initial steps to consider. "

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//https://librarycarpentry.org/Top-10-FAIR/"
author:             "librarycarpentry"
twitter:
  username:         "LibCarpentry"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "https://librarycarpentry.org/Top-10-FAIR/"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "//librarycarpentry.org/Top-10-FAIR/about"
  - name:           "Download (Not Yet Available)"
    href:           "//librarycarpentry.org/Top-10-FAIR"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
