# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Top 10 FAIR Data & Software Things"
description:        "The Top 10 FAIR Data & Software Things are brief guides (stand alone, self paced training materials), called "Things", that can be used by the research community to understand how they can make their research (data and software) more FAIR (Findable, Accessible, Interoperable and Reusable)."

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "https://librarycarpentry.org/Top-10-FAIR/"
author:             "librarycarpentry"
twitter:
  username:         "LibCarpentry"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/Top-10-FAIR/about"
  - name:           "GitHub Repository"
    href:           "https://github.com/LibraryCarpentry/Top-10-FAIR"
  - name:           "Download/Cite"
    href:           "http://doi.org/10.5281/zenodo.3409968"
  - name:           "License"
    href:           "/Top-10-FAIR/license"
  - name:           "#Top10FAIR"
    href:           "https://twitter.com/search?f=tweets&vertical=default&q=%23top10fair&src=typd&lang=en"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
